<?php if (!defined('HKCMS_VERSION')) exit(); ?>
<style type="text/css">
    body,h1,ul{
        margin:0;
        padding:0;
            }
            body{
                background-color: #fff;
            }
            ul{
                list-style: outside none none;
            }
            a{
                text-decoration: none;
            }
            .conainer{
                max-width: 1080%;
                margin: 0 auto;
            }
            .fl{
                float: left;
            }
           .fr{
            float: right;
           }
           .top-nav{
            background:#eee;
           }
           .top-nav .item{
            display: inline-block;
            padding: 6px 10px;
            color: #666;
           }
           .top-nav .item:hover{
            color: #333;
             }

</style>
<header>
    <div class="top-nav clearfix">
        <div class="container">
            <div class="fl">
                <a class="item" href="#">首页 </a href="#">
            </div>
        <div class="fr">
           <a class="item" href="#">我的订单</a href="#">
            <a class="item" href="#">收藏夹 </a href="#">
            <a class="item" href="#">登录</a href="#">
             <a class="item" href="#">注册</a href="#">
        </div>
      </div>
    </div>
</header>
